### ISSUE TITLE
Investigate JS / Graph API integration to support New Outlook for Windows

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#1734]
As [confirmed by Microsoft](https://techcommunity.microsoft.com/t5/outlook-blog/add-ins-in-the-new-outlook-for-windows/ba-p/3954388), COM add-ins are deprecated and third-party tools have to use web add-ins (JS or Graph).

:link: https://learn.microsoft.com/en-gb/office/dev/add-ins/outlook/one-outlook

This would be a _significant_ change to OGCS...

As taken from [Will the new Outlook for Windows replace Windows Mail and Calendar?](https://www.microsoft.com/en-us/microsoft-365/outlook/outlook-for-windows):  
> Beginning in 2024, new Windows 11 devices will be shipped with the new Outlook for Windows as the default mailbox application free for all to use. The Mail and Calendar applications will continue to be available via download in the Microsoft Store through the **end of 2024**. On existing devices, users can switch to the new Outlook for Windows from a toggle in the Mail and Calendar applications.

###  To-do
- [x] Research JS APIs and viability :x: 
   - [x] A [JS Web API](https://learn.microsoft.com/en-us/javascript/api/outlook?view=outlook-js-preview) add-in is aimed at interacting with individual items (email or meeting) in focus and allowing further functionality to be added. Furthermore, the functionality would only be available as the user interface (New Outlook/Outlook on the Web) is interacted with - it is not for unattended automation or access to an entire calendar in order to sync its content on a schedule.
   - [Supported scenarios in Outlook web add-ins](https://learn.microsoft.com/en-gb/office/dev/add-ins/outlook/one-outlook#supported-scenarios-in-outlook-web-add-ins) - none apply
   
- [x] Research [Graph APIs](https://learn.microsoft.com/en-gb/graph/api/resources/mail-api-overview?view=graph-rest-1.0) and viability :heavy_check_mark: 
   - [x] Supports Exchange Online and hybrid Exchange
> The Microsoft Graph API supports accessing data in users' primary mailboxes and in [shared mailboxes](https://support.office.com/article/open-and-use-a-shared-mailbox-in-outlook-d94a8e9e-21f1-4240-808b-de9c9c088afd). The data can be calendar, mail, or personal contacts stored in a mailbox in the cloud on Exchange Online as part of Microsoft 365, or on Exchange on-premises in a [hybrid deployment](https://learn.microsoft.com/en-us/graph/hybrid-rest-support).
> 
> The API does not support accessing in-place archive mailboxes, not [on Exchange Online](https://learn.microsoft.com/en-us/microsoft-365/compliance/enable-archive-mailboxes) nor [on Exchange Server](https://learn.microsoft.com/en-us/Exchange/policy-and-compliance/in-place-archiving/in-place-archiving?view=exchserver-2019&preserve-view=true).

- [x] [Exchange Web Services](https://learn.microsoft.com/en-us/exchange/client-developer/exchange-web-services/start-using-web-services-in-exchange) :x: 
   - Deprecated since 2018 and [should be migrated to Graph](https://learn.microsoft.com/en-us/graph/migrate-exchange-web-services-overview).
   - It does however support on-premises Exchange Server 2007 and newer.

### Summary
* Graph API is the only viable way forward
* Using Graph API would remove the need for a fat Outlook client entirely
   * New Outlook is therefore moot; OGCS just needs to access cloud mailboxes
   * No security popups
   * No COM errors due to bad Office install
* Object model will completely change
* Exchange on-premises and legacy managed servers would have to have their employees continues to use the old desktop Outlook clients, which [still support COM addins](https://learn.microsoft.com/en-gb/office/dev/add-ins/outlook/one-outlook#impact-on-vsto-and-com-add-ins).

:link: #1640

**Comment by abhasin505** [comment]
Hi @phw198 - is there an eta for releasing the Graph API support?

**Comment by phw198** [comment]
No, but you can [keep track of the project](https://github.com/users/phw198/projects/2) and when it gets to a point where I can make early development releases - thanks for your interest!

**Comment by vatioz** [comment]
Does it make sense to include information about currently broken COM integration with new Outlook client on the main project page (https://www.outlookgooglecalendarsync.com) as well as on the main github page (https://github.com/phw198/OutlookGoogleCalendarSync)?   
As a developer, I was able to go to github issues and read through few of them and find out what is the problem with the application. But I can see that many users wouldn't be able to do the same and there is no easy way for general user to find out (and possibly track progress towards the resolution).

Of course I am very greatful for all the work on this project and very much appreciate the ongoing work on the current issue.

**Comment by phw198** [comment]
Yes, you are absolutely right @vatioz - it seems Microsoft are moving forward at pace, pushing out New Outlook with a new toggle button appearing in the semi-annual release channel already!

I'll make it much clearer switching will break OGCS at the moment.

For info, below is MC703703 from 4-Jan-2023:-

-----

## Toggle to try the Preview of new Outlook for Windows in Semi-Annual Channel

In Spring 2023, we expanded access to the preview of the new Outlook for Windows to users in Current Channel and Monthly Enterprise Channel. In September, this toggle was also released to Semi-Annual Channel Preview. The experience is an option to try, and nothing will change without end users taking action. We will give notice before any required changes occur, after the preview has received sufficient usage and feedback.

### When this will happen:

Rollout will be in January with the release of a new build to Semi-Annual Channel

### How this will affect your organization:

End users in the classic Outlook for Windows (desktop app) will see a toggle in the upper right to 'Try the new Outlook’. This toggle will be available for all users in Semi-Annual Channel who have supported accounts. Currently, supported accounts in the new app are Microsoft Exchange Online, Outlook.com, Google, Yahoo, iCloud, and IMAP accounts.

Note: The new client is still a preview experience, and the default state of the toggle to try it is OFF. Users may submit feedback about any capabilities they are missing if they need to switch back to the classic experience.

### What you need to do to prepare:

Review policies your organization has configured for Exchange mailboxes, which governs the configuration of the new Outlook. See this document for more information: [Policy Management - Deploy Office | Microsoft Learn](https://learn.microsoft.com/deployoffice/outlook/manage/policy-management)

We recommend reviewing any remaining COM/VSTO add-ins used by your organization and moving to web add-ins because COM/VSTO add-ins will not be supported in the new app. Otherwise, no actions are required. See this document for more information: [Migrate from COM to web add-ins - Deploy Office | Microsoft Learn](https://learn.microsoft.com/deployoffice/outlook/get-started/migrate-com-to-web-addins)

If you are not ready for this preview in your organization, there are options to control the release, either by hiding the toggle or disabling mailbox access. See this document for more information: [Deployment overview for the new Outlook for Windows - Deploy Office | Microsoft Learn](https://learn.microsoft.com/deployoffice/outlook/get-started/deployment-new-outlook#control-release-of-the-new-outlook)

**Comment by phw198** [comment]
> I'll make it much clearer switching will break OGCS at the moment.

A section was added to the project homepage, stating OGCS does not work with New Outlook.

However, for early development builds of a version that doesn't require the Outlook client to sync, please see:-
- #1881
