### ISSUE TITLE
Create a Graph app registration

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#1737]
* [AAD App Registration](https://learn.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration)
* [MSAL for Desktop](https://learn.microsoft.com/en-us/entra/identity-platform/reference-v2-libraries#desktop-application) - [Tutorial](https://learn.microsoft.com/en-us/entra/identity-platform/tutorial-v2-windows-desktop)

Other
* https://learn.microsoft.com/en-us/graph/auth-register-app-v2

### Tasks
- [x] Create basic app registration
- [x] Verify OGCS domain ownership
- [x] Assign scopes
- [ ] ~~Fully customise the app once working~~ Seems very limited, eg no logo, assumed because cannot verify as publisher
- [ ] ~~Perform [publisher verification](https://learn.microsoft.com/en-gb/entra/identity-platform/publisher-verification-overview)~~ - only possible for work or school tenant accounts with custom domains
