### ISSUE TITLE
Authenticate through app registration with .NET MSAL

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#1742]
### Tasks
- [x] Use sample program to test out app registration
   - [ ] ~~Make custom logo etc show~~ - maybe not possible for unverified publishers?
- [x] Build code into OGCS project
- [x] Update the Outlook settings GUI page
   - [x] Show the Microsoft account name
- [x] [Serialize the token](https://learn.microsoft.com/en-us/entra/msal/dotnet/how-to/token-cache-serialization?tabs=desktop) for persistence
- [ ] ~~Store UPN in settings~~
- [x] Add masking for any logging
- [x] Disconnect account
