### ISSUE TITLE
Log Sanitizer

### ISSUE THREAD

**Issue by rhonabwymcneill** [phw198/OutlookGoogleCalendarSync#1755]
Hi,

I have a slight problem with the debug log, namely that I'd like to send it with bug reports, but since I use OGCS to sync private and work calendar I'd need some kind of "sanitizer" feature to remove IDs, calendar item headlines and so on (everything which could be used to identify 3rd parties more or less). Is there a way to do this or could this maybe be added as a feature?
(I tried to use the word obfuscation feature for it, but it looks like the words still get written to the log)

Thanks and best regards

----
### Tasks
- [x] Anonymise Google subjects
- [x] Anonymise Outlook subjects
- [x] Anonymise modified attributes summary
    - [x] Subject
    - [x] Subject attribute when changed
- [x] New GUI setting

**Comment by phw198** [comment]
:package: This is probably a never ending aspiration, but I've made a good start with a new option to anonymise the calendar subjects - have a go with [hotfix v2.10.2.14.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/13759543/v2.10.2.14.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/11843015/6e51b50e-008a-4a8f-80cf-44e074165823)

Please let me know how it goes.
