### ISSUE TITLE
Tracking issue for all CodePlex references

### ISSUE THREAD

**Issue by SeanKilleen** [phw198/OutlookGoogleCalendarSync#253]
Figured I would start this. Can split it out into other issues if you want, but I figured this would be a good issue to serve as an umbrella for multiple PRs.

* [x] [In Social.cs](https://github.com/phw198/OutlookGoogleCalendarSync/blob/02cd0db20ebc6179443bd521f981a5f166b2c838/src/OutlookGoogleCalendarSync/Social.cs#L33): A reference to the RSS feed for releases. I believe if you turn on Github releases and make use of them eventually, a similar link is possible that could be updated here.
* [x] [In README.md](https://github.com/phw198/OutlookGoogleCalendarSync/blob/b5cb26c0ae3bb3872c85c8ee3f02b2fafacce054/README.md#L11) : References to the CodePlex clickonce installer. to be removed once you're using a different source (Squirrel or something along those lines).
* [x] [In Updater.cs](https://github.com/phw198/OutlookGoogleCalendarSync/blob/e4a1efdd4e918946473ea524ff6c5663d0dbab9c/src/OutlookGoogleCalendarSync/Updater.cs#L57): References to `legacyCodeplexCheck()`. May still be needed; not sure. 
* [x] [In ApiKeyring.cs](https://github.com/phw198/OutlookGoogleCalendarSync/blob/02cd0db20ebc6179443bd521f981a5f166b2c838/src/OutlookGoogleCalendarSync/ApiKeyring.cs#L18): Reference to the API keyring as part of the codeplex address.
* [x] [In the .csproj](https://github.com/phw198/OutlookGoogleCalendarSync/blob/e4a1efdd4e918946473ea524ff6c5663d0dbab9c/src/OutlookGoogleCalendarSync/OutlookGoogleCalendarSync.csproj#L36): Reference to the installer pointing to codeplex.com
 * [x] [In the MainForm.Designer](https://github.com/phw198/OutlookGoogleCalendarSync/blob/02cd0db20ebc6179443bd521f981a5f166b2c838/src/OutlookGoogleCalendarSync/MainForm.Designer.cs.orig#L294): reference to the project on a label.
* [x] [In Program.cs](https://github.com/phw198/OutlookGoogleCalendarSync/blob/02cd0db20ebc6179443bd521f981a5f166b2c838/src/OutlookGoogleCalendarSync/Program.cs#L361): A reference to opening the release notes directly on hard-coded codeplex URL.
* [x] In [OutlookCalendar.cs](https://github.com/phw198/OutlookGoogleCalendarSync/blob/02cd0db20ebc6179443bd521f981a5f166b2c838/src/OutlookGoogleCalendarSync/OutlookCalendar.cs#L862), opening a hard-coded codeplex page on a COM error.
* [x] [In MainForm.cs](https://github.com/phw198/OutlookGoogleCalendarSync/blob/e4a1efdd4e918946473ea524ff6c5663d0dbab9c/src/OutlookGoogleCalendarSync/MainForm.cs#L1705), a hard-coded codeplex URL when the issue link is clicked on.

**Comment by phw198** [comment]
Thanks @SeanKilleen, I think these are all covered in the next release, which should be out weekend 8/9th July.
